### PR TITLE
Added Ethos Overdrive Pedal

### PR DESCRIPTION
**Pull request by josephpatrickrose**
first attempt...

### CODE REVIEW

**Comment by tehtrav** [comment]
Do you mind cleaning up the Ethos OD photo? The background should be knocked out and transparent like the other pedals.

**Comment by tehtrav** [comment]
I have used Pixelmator and Photoshop — not sure about the free offerings

**Comment by josephpatrickrose** [comment]
OK I have used Super Photo Cut and uploaded the changes.

**Comment by josephpatrickrose** [comment]
can these changes please be committed now ? thanks.

**Comment by josephpatrickrose** [comment]
Hi Travis,
Something has gone a bit screwy with pedalplayground today. Opened the web page and the pedalboards themselves are showing, but the pictures of the pedals are chopped up and all over the place... luckily I printed out my last layout.

Browser in question is Google Chrome 67.0.3396 on a Macbook Pro, OS X 10.13.6 Beta.

Regards
Joe

**Comment by tehtrav** [comment]
This has been merged in but because there are extra transparent pixels around the image it will not appear to be the right size. I can't fix it until later.

**Comment by tehtrav** [comment]
@josephpatrickrose I released an update to pedalplayground that will nuke old layouts — I wrote about the update here: https://www.thegearpage.net/board/index.php?threads/i-made-a-new-pedalboard-planning-tool-pedalplayground-com.1803507/page-35#post-26704784

**Pull request merged**
