### PR TITLE
Added Source Audio and Walrus pedals

### PR DESCRIPTION
**Pull request by einargi**
Source Audio Spectrum
Walrus Audio Fathom

### CODE REVIEW

**Comment by tehtrav** [comment]
The Fathom has too much transparent pixels around the image, which will cause it to show up too small. Please trim that and then I will approve!

**Comment by einargi** [comment]
Hopefully it came through correctly this time

**Comment by tehtrav** [comment]
Merged!

**Comment by einargi** [comment]
I’m really sorry - there’s a comma missing after “Fathom” which probably broke the drop down

**Comment by tehtrav** [comment]
No worries!

**Pull request merged**
