### PR TITLE
Added EQD Hizumitas

### PR DESCRIPTION
**Pull request by CrowStudio**
New coming pedal from EarthQuake Devices: https://www.earthquakerdevices.com/hizumitas

### CODE REVIEW

**Comment by ArislanShiva** [comment]
I already added this in my last PR

**Comment by CrowStudio** [comment]
Hehe, sorry for the trouble.
Keep up the good work!

Beat regards/Daniel

**Comment by CrowStudio** [comment]
I'm a bit new to this pull request thingy, should've checked the cue first
🙄

**Comment by ArislanShiva** [comment]
Hey NP!  Can go ahead and close this PR btw 😉

**Comment by CrowStudio** [comment]
Missed that the EQD Hizumitas already was added to pull request #670

**Pull request closed without merging**
