### PR TITLE
Adds Ampeg, BOSS, Catalinbread, Darkglass, Donner, EarthQuaker Devices, Friedman, J. Rockett, Jackson Audio, Keeley, Line 6, and ThorpyFX pedals

### LINKED ISSUE #1513: please add PastFX powerbooster
it's like the only one of theirs you havn't added

fiq7jpztuyl0cbh5s5wz

Dimensions: 112 x 60 x 31mm / 4.4" x 2.36" x 1.22

### LINKED ISSUE #1514: Please add Boss gt 1
I seen the most other gt multi effects added, not sure why gt 1 hasn’t been added yet. Please and thank you

### LINKED ISSUE #1540: Pedal request please : FORMULA B Supa Tank
Can you add this pedal please ?
**FORMULA B** Supa Tank 
Height 5,51 inches
Width 3,15 inches

formula-b-supa-tank-muff

### LINKED ISSUE #1553: Pedal request please : FORMULA B Supa Tank
Can you add this pedal please ?
FORMULA B Supa Tank
Height 5,51 inches
Width 3,15 inches

243116887-028ecc29-d592-46c0-8c39-57b11e56a671

### LINKED ISSUE #1560: Pedal request: Boss RC-2 Loop Station
IMG_3609

### LINKED ISSUE #1573: Pedal Request: BBE MS-92 Mini Sonic Stomp
BBE MS-92 Mini Sonic Stomp

1.25" x 3.5"

### PR DESCRIPTION
**Pull request by XlosVSM**
**Adds**
- Ampeg SGT-DI
- BBE Sonic Stomp Mini
- BOSS GT-1
- BOSS ME-90
- BOSS RC-2
- Catalinbread Sabbra Cadabra (Clearwell Edition)
- Catalinbread Soft Focus Reverb (Shoegaze Purple)
- Darkglass NSG
- Donner Circle Looper
- Donner Dark Mouse
- Donner Dumbal Drive
- Donner Extreme Driver
- Donner Golden Tremolo
- Donner Island Delay
- Donner Morpher
- Donner Vintaverb
- EarthQuaker Devices Aurelius
- EarthQuaker Devices Special Cranker (Blue Steel)
- Electro-Harmonix Lizard Queen (Big Box)
- Formula B Supa Tank
- Friedman BE-OD (Artisan Edition)
- Friedman BE-OD Deluxe (Clockworks Edition)
- Friedman Sir-Compre (Artisan Edition)
- Fulltone GT-500
- GUPTech SUN
- J. Rockett Audio Designs The Jeff Archer (Copper Plated)
- Jackson Audio Golden Boy (Rose)
- Keeley Halo (Andy Apple Red)
- Keeley Katana (New Light Pink)
- Kingsley Page TS
- Line 6 Helix (Space Gray)
- Mooer TF-16S
- MOYO Mini Expression
- MOYO Mini Volume
- PastFX Patriarch
- PastFX Powerbooster
- Pladask Elekstrisk Falma V2
- Sonuus Voluum
- ThorpyFX ER-2 Uni-Vibe

**Fixes**
- BOSS ML-2 item name
- Death by Audio Interstellar Overdriver image
- Dimensions of some Donner pedals
- DOD Carcosa image improved
- DOD moved to its own brand
- File name changes for spelling
- GigRig Three 2 One dimensions
- MXR Super Comp duplicate removed
- MXR Super Comp image improved
- Restores brands on some pedals
- Restores Retro-Sonic images
- ThorpyFX brand name capitalised properly
- Twinote BBD Chorus dimensions

closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1251
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1443
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1446
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1453
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1469
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1472
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1473
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1483
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1484
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1485
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1486
closes #1513 
closes #1514 
closes #1540 
closes #1553 
closes #1560 
closes #1573

### CODE REVIEW

**Comment by XlosVSM** [comment]
@tehtrav when will this be merged?

**Review by ArislanShiva — CHANGES_REQUESTED** [review]
I added the new Diamond pedals with better art and correct dimensions in my PR.

**Comment by ZYMECORE** [comment]
Will this be merged soon? The initial commits are 4 months old!

**Comment by XlosVSM** [comment]
@tehtrav will this be merged soon?

**Pull request closed without merging**
