### PR TITLE
Added Stomp Audio Labs Octopus

### PR DESCRIPTION
**Pull request by jjtguitar**
I think this is the route I need to take to contribute a pedal to the playground? I've uploaded the images and info as per the readme to my fork, now making a pull request. Sorry if I'm doing this wrong.

### CODE REVIEW

**Comment by ArislanShiva** [comment]
Did you mean to censor out words in the json?

**Comment by jjtguitar** [comment]
No. I didn’t actively do that, but I noticed it after I had added my entry

**Review by ArislanShiva — CHANGES_REQUESTED** [review]
Please change those back and re-upload.  Thanks!

**Comment by jjtguitar** [comment]
I think these were already censored. I didn't change any of those. I just added my info for the pedal I'm trying to add. Looking at the master copy of the json, those entries are already censored.

**Comment by ArislanShiva** [comment]
The changes are only on [your branch](https://github.com/PedalPlayground/PedalPlayground.github.io/pull/1384/files).

You may have some kind of language filter on whatever program you used to edit the json?

**Comment by ArislanShiva** [comment]
Glad you were able to figure it out!

Now just gotta wait for the site owner to pull your changes into the database.

**Review by ArislanShiva — APPROVED** [review]

**Comment by jjtguitar** [comment]
I can't find the added pedal in the list on Pedalplayground.com - is there something I need to do to make updates work? Stomp Audio Labs Octopus.

**Pull request merged**
