### PR TITLE
Added Analog.man + Daredevil + Diamond + Fuzzrocious + Interstellar Audio Machines + Land Devices + Pedaltrain + Subdecay + New Pedals + Misc Requests

### LINKED ISSUE #1204: Pedalboard Request Daddario XPND1 and XPND2
XPND1
https://www.daddario.com/products/accessories/xpnd-pedalboards/01-xpnd-pedalboard/item/daddario-xpnd-pedalboard-01-9893/
Dimensions retracted (W x H x D): 34.92 x 6.53 x 14.86 cm (13.75" x 2.57" x 5.85")
Extended dimensions (W x H x D): 62.67 x 6.53 x 14.86 cm (24.75" x 2.57" x 5.85")

XPND2
https://www.daddario.com/products/accessories/xpnd-pedalboards/01-xpnd-pedalboard/item/daddario-xpnd-pedalboard-02-9894/
Retracted dimensions (W x H x D): 44.45 x 9.9 x 32.5 cm (17.5" x 3.9" x 12.8")
Extended dimensions (W x H x D): 80.65 x 9.9 x 32.5 cm (31.75" x 3.9 x 12.8")

### LINKED ISSUE #1416: Pedal Request: Keith McMillen Instruments - 12 Step
Please add the KMI 12 Step MIDI controller pedal. Dimensions are 17" x 4.5".
12-step-1

### LINKED ISSUE #1432: Pedal Request: Blackhawk Amplification Balrog Distortion
Brand: Blackhawk Amplification
Model: Balrog Distortion
Size: 2.59 x 4.94
Balrog Distortion (Blackened)

### LINKED ISSUE #1448: Pedal Request
Hello - Request to add Pedal to Pedal Playground
Sabbadius Funky Vibe (7.5 x 5)
Funky Vibe

### LINKED ISSUE #1480: Added Stomp Audio Labs Octopus #1384 - can't see it in the Playground?
I added Stomp Audio Labs Octopus, added the info and images as specified in the contributing info. The request was (I think) approved and merged two weeks ago, but the pedal I added does not appear in the Playground. I checked the json file, and the pedal is there. Not sure if there is something I need to do to make it appear in the list of pedals?

### LINKED ISSUE #1488: Jetter Red Square
Jetter Red Square
4 7/8" W x 4 3/8" H
Jetter Red Square

Thanks!

### LINKED ISSUE #1490: Aion FX Andromeda
same dimensions as Aion FX Stratus Classic Overdrive (2.59843 x 4.80315)
andromeda__top-1200px

### LINKED ISSUE #1492: Radial JDX Direct-Drive
Radial JDX Direct-Drive

site:
https://www.radialeng.com/product/jdx-direct-drive/features

### LINKED ISSUE #1505: Damnation Audio pedals
Please add images of Damnation Audio pedals

### LINKED ISSUE #1507: Pedal Request: Oneder Effects Old Blue
Oneder Effects Old Blue
W: 2.6"
H: 4.97"
image_54826bab-db5d-420d-b69e-9abcde61caa2_1024x1024

### LINKED ISSUE #1508: Pedal Request: Peterson Strobostomp Mini
Peterson Strobostomp Mini
W: 1.8"
H: 3.7"
Screenshot 2023-05-03 at 1 03 36 AM

### LINKED ISSUE #1509: Pedal Request: FMR Really Nice Compressor
FMR Really Nice Compressor

5.5" x 6.0" with protrusions included.

Stereo compressor that is pedal board size and leaves room on top to stack pedals. Since the knobs stick out so far, I'd appreciate it being added to the database, as making a custom black box doesn't quite show an accurate representation of space available in the corners.

### LINKED ISSUE #1510: Warm Audio Foxy Tone (dimensions are wrong)
Just bought a Warm Audio Foxy Tone yesterday.
Found out it's a bit bigger than it currently is on PedalPlayground.
It's a bit of a weird pedal since the knobs and switch are on the sides of the pedal.

The correct dimensions are:
width: 6,5"
length: 3.7" (box) or 4.7" (box incl. knobs/switch/jack on outside)

### LINKED ISSUE #1511: Pedal Request: Sonicake Octaver

### LINKED ISSUE #1512: Pedalboard request: D’addario Xpand 1 & 2
Maybe since these have variable lengths, maybe we could have a few different options for each? Or at least maximum and minimum sizes?

### LINKED ISSUE #1515: Pedal Request: J Rockett Univ-Verb
Screenshot 2023-04-17 at 8 05 35 PM

4.75″X5.25″X1.25 (2.25″ to top of knob”)

Thanks in advance

### LINKED ISSUE #1516: Pedal Request: Pigtronix Resotron
Screenshot 2023-04-17 at 8 05 01 PM

4.5"L 1.5"W 2.5"H

Thanks in advance

### LINKED ISSUE #1517: TC Helicon VOICETONE HARMONY-G XT
VOICETONE-HARMONY-G-XT_P0CMT_Top_XL

Height: 5.25 inches (132 mm)
Width: 5 inches (130 mm)

Thanks in advance

### LINKED ISSUE #1519: Donner Tutti Love - incorrectly scaled
It displays vertically shorter than it should be.

### LINKED ISSUE #1520: Tonecity Model M pedal Request
I am looking for the Tonecity Model M pedal to be added

### LINKED ISSUE #1521: Diamond Boost-EQ
Would love to see the Diamond Boost-EQ added. I just bought one on special when the brand had gone under, but now that Empress is bringing them back, here's hoping it comes back into production. Fantastic Tilt EQ with selectable mids and a very nice amount of gain on tap. 
boost-eq
Boost-EQ small

### LINKED ISSUE #1522: Keeley Delay Workstation
Same dimensions as other Keeley Workstation pedals (4.7" w x 3.7" h). Thanks!

Delay Workstation

### LINKED ISSUE #1523: Sabbadius Funky Vibe
Would love to see this line added to the options.

https://www.sabbadius.com/?page_id=70&lang=en

They make a few options, mainly the 69 and the fillmore, then they make a smaller size as well.

### LINKED ISSUE #1524: Stone Deaf FX Q Boost (Limited Edition)
It would be really helpful to have this new version in the system. I'll leave the 800px png, if someone was so kind as to put it up.
![Stone-Deaf-FX-QBoost-Limited-Edition]

I believe these are the dimensions:

Width: 2.83 in
Height: 4.53 in

(https://github.com/PedalPlayground/PedalPlayground.github.io/assets/133849488/b8700fa8-ca3a-48c6-b502-017837296145)

### LINKED ISSUE #1525: Dr Scientist BoostBot
BoostBot_Main_Alt-1024x1024

Dimensions: 2.8” wide with jack and side knob, 2.0” long, 1.7” standing off the board

### LINKED ISSUE #1526: Please Add: JDM Pedals Humdinger
Dimensions 4.73 inches wide, 3.81 inches tall including top mount jacks

### LINKED ISSUE #1527: Please Add: Orange Amp Detonator
Dimensions
Height:
2.56"
Width:
3.74"
Depth:
5.12"

Same as other Orange pedals.

image

### LINKED ISSUE #1528: Please Add: ENO Music EX EQ7 Equalizer Pedal
Brand: ENO Music (also sold under the Ammoon brand)
Name: EX EQ7 Equalizer Pedal

More info: https://www.modulargrid.net/p/eno-music-ex-eq-7-equalizer

Dimensions:

With Jacks:

Width: 46.75 mm / 1.84 in 
Length: 96 mm / 3.8 in

Without Jacks:

Width: 40 mm / 1.55 in
Length: 95 mm / 3.72 in

image

### LINKED ISSUE #1529: Electro Harmonix / Sovtek Green Russian Big Muff Pi V7
Electro Harmonix / Sovtek Green Russian Big Muff Pi V7

EHX_Big_Muff_V7c_2nd_edition

width: 5in
length: 6.75in

### LINKED ISSUE #1530: Please add: Mod Audio Dwarf
Brand: Mod Audio
Model: Dwarf
Height: 105mm / 4.134in
Width: 202mm / 7.953in

moddwarf

### LINKED ISSUE #1531: Please add: Darkglass Hyper Luminal LTD BLK
A bass compressor pedal by Darkglass.
It's the same as the silver/normal edition (which already exists here) but just in black:
https://www.thomann.de/de/darkglass_hyper_luminal_comp._ltd_bk.htm?gclid=Cj0KCQjwjryjBhD0ARIsAMLvnF-v2PH_Bx3zNjni_M5EfaIIZa5IGPnbZAM4C_CPKn-bTcKUNjnzNkUaAnQ6EALw_wcB

### LINKED ISSUE #1532: Please add: Sonicake Noise Wiper
A noise gate by Sonicake:
https://www.sonicake.com/products/noise-wiper

Front view image:
https://www.modulargrid.net/p/other-unknown-sonicake-noise-wiper

Dimensions:
Length: 9,3cm  
Width: 4,2cm 
Height: 5,2 cm

### LINKED ISSUE #1533: Please add: Diamond Memory Lane The dBBD Delay
https://www.diamondpedals.com/en-ca/products/memory-lane

### LINKED ISSUE #1534: Animals Rover Fuzz (V1)
Hi, hoping we could add V1 since the existing Animals Rover Fuzz is V2. Same dimensions for the two pedals. Thanks!!

Rover V1

### LINKED ISSUE #1535: Templo Devices!
Y'all need to add the handful of pedals from Templo Devices! NOMAD amp obviously not, and probably not the Pocket Studio Compressor.. But this Canadian company is making WAVES with the Reel Deal and the Reel Dealuxe, the SPLYCE, the Triplo, and the Model 33. One of the coolest new companies out there. 
I can't seem to get my computer to upload anything other than a .webp file, glitchy thing I've got. But these guys are doing great things and I know JHS' show will only gain them more popularity.

### LINKED ISSUE #1537: Daily Driver!
Would love to see the Shnobel Tone Daily Driver added!
Shnobel-Tone-Daily-Driver-Overdrive
a9c630_1c5dd64610fb459c87c2d5b066b6e81d~mv2

### LINKED ISSUE #1538: Homebrew Electronics Power Screamer
Hi, Please add Homebrew Electronics Power Screamer
Size is: 4.7 * 3.7 inch

image

Thanks!

### LINKED ISSUE #1541: Please add: Analog.man Block Logo Envelope filter
The dimensions are: 2 5/16" x 4 5/16"

AMEnvelope Filter

### LINKED ISSUE #1542: Pedal request: Dut Beardy Admiral (Midi switch, ML5 analog)
Dimensions are like a standard MXR sized box
Admiral

### LINKED ISSUE #1543: Pedal request : Palmer Pocket Amp MkII
Palmer Pocket Amp MkII
Dimensions : 3,93 in x 3,93 in / 100 mm x 100 mm

Sans titre

### LINKED ISSUE #1544: Pedal request: Electro-Harmonix Deluxe Electric Mistress (big box)
peghgzezsbdnp4vj3azg

Dimensions 8" wide, 6.5" long and 2.5" tall, same as Deluxe Memory Man (big box)

### LINKED ISSUE #1545: Pedal request: Electro-Harmonix Q-Tron (big box)
Dimensions: 8" wide, 6.5" long and 2.5" tall (same as DMM big box)

electro-harmonix-q-tron-original-5988

### LINKED ISSUE #1548: Pedal Request: Blue Colander Pig
Brand: Blue Colander
Model: Pig
Size: 2.6 x 5
Screenshot 2023-06-09 at 12 34 37 AM

### LINKED ISSUE #1551: Pedal Request: Does it Doom Doomcaster
Brand: Does it Doom
Pedal: Doomcaster
Dimensions: 4.75” x 2.625” x 2.375”

1efztph957j71

### LINKED ISSUE #1552: Pedal request: Bluguitar Amp1 Iridium Edition
Same dimensions as the silver edition: 9.65 x 7.56 inches

IMG_0127

https://bluguitar.com/en/products/amp1/amp1-iridium-edition

### LINKED ISSUE #1554: Please Add:
Effectrode Mercury Fuzz

3.75" W x 4.75" H

Thanks!

effectrode-tf-2a-mercury-fuzz

### LINKED ISSUE #1555: Pedal Request: DOD FX50
5.13x3.3
Screenshot 2023-06-21 at 12 44 45 PM

### LINKED ISSUE #1556: Pedal Request: Keeley Time Machine
4.7x3.82
KTMB-large

### LINKED ISSUE #1557: Pedal Request: Hotone Ampero Mini
Can you please add this pedal?

Hotone Ampero Mini

Dimensions: 5.27" (W) × 4.72" (D) × 1.9" (H)

Ampero_Mini_Hotone

Ampero_Mini_Hotone_purple-removebg-preview

### LINKED ISSUE #1559: Pedal request: Boss SDE-3000D Dual Digital Delay
IMG_3610

### LINKED ISSUE #1561: Pedal request: VS Audio Platinum
IMG_3615

### LINKED ISSUE #1562: Pedal request: Tru-Fi Floyd Fuzz (Ram's Head version)
Dimensions:
5.5" tall
3.59" wide
Tru-Fi Floyd Fuzz

### LINKED ISSUE #1563: Pedal Request: PaulC Tim V3
Screenshot 2023-06-26 at 9 37 50 AM

Please add the Paul Cochrane Tim V3. 3.75" x 4.58" without jacks. Thanks!

### LINKED ISSUE #1567: Pedal request: Roger Mayer Voodoo Vibe
artworks-000244182138-4t143z-t500x500

### LINKED ISSUE #1568: Pedal Requests: Free the Tone PHV-1 Phase Inverter and Lwave Tiny Tap
Dimensions: (W) 3.68 x  (D) 2.08"

Nice phase corrector solution for stereo pedalboards. Supplied dimensions include protrusions.

Screenshot 2023-06-30 at 1 05 59 AM

Dimensions: (W) 1.26 x (D) 1.18"

Great extremely small tap tempo.

### LINKED ISSUE #1569: Pedal Request : Providence - System Tuner STV-1JB
Brand : Providence
Model : System Tuner STV-1JB
Dimensions : 2.99 x 4.53 inches (76 x 115 mm)
stv1jb

### LINKED ISSUE #1570: Pedal Requests : Warwick Tres 3.3 pedalboard, Musicomlab Parallellizer, Cioks DC10 Link, SS/BS mini silver, Pladask Elektrisk Fabrikat w/ Gold Faceplate
Tres 3.3: 

Dimensions:  722 mm (W) / 28 27/64"
                     236 mm(D) / 9 19/64"

--

Musicomlab Parallellizer:

 Dimensions : 160(W) x 96(D) mm
                       6.3(W) x 3.8(D) inches

You have the SSBS and Pladask ones already.

tres3 3

### LINKED ISSUE #1571: Pedal Request: Twilight Pulse Audio Proxima
https://twilightpulseaudioworks.bigcartel.com/product/proxima

### LINKED ISSUE #1572: Pedal Request: Analog.Man Bad Bob mini
bad bob mini

Please add the Analog.Man Bad Bob mini. Thanks!

### LINKED ISSUE #1574: Pedalboards request: Pedaltrain XD series
Please add the new Pedaltrain XD series: the XD-18 and XD-24.

XD-24: 24 in x 17.5 in.

https://pedaltrain.com/collections/new-models/products/pedaltrain-xd-24

XD-18: 18 in x 17.5 in

https://pedaltrain.com/products/pedaltrain-xd18-with-soft-case

### LINKED ISSUE #1575: Pedal Request: Analog.man Envelope Filter
z707g7gc

### LINKED ISSUE #1576: Pedal request: Jam Pedals Fuzz Phrase ltd
Dimensions: 2.9 x 4.7 x 2.2 inches
fuzz-phrase-ltd

### LINKED ISSUE #1577: Pedal request
Please add the 1981 Inventions LVL 
Screen Shot 2023-07-13 at 12 37 02 AM

### LINKED ISSUE #1578: Pedal Request: E.W.S. Little Fuzzy Drive
Dimensions 3.64 x 1.89

ewslittlefuzzydrive

### LINKED ISSUE #1579: Pedal Request: Effectrode TF-3A Mercury Fuzz
Dimensions 5.06 x 3.75 including top jacks and switch
effectrodetf3amercury

### LINKED ISSUE #1580: Pedal Switcher/Looper Request
Moen GEC5

Dimensions:
260mm x 88mm
10.2362" x 3.4646"

moen
GEC5_2

### LINKED ISSUE #1581: Pedal Request: Hello Sailor Effects Rangemaster
Dimensions 4.8 x 3.47
hellosailoreffectsrangemaster

### LINKED ISSUE #1582: Pedal Request: Electro-Harmonix Andy Summers Walking on the Moon Flanger
Electro-Harmonix Andy Summers Walking on the Moon Flanger

4" x 4.75"

### LINKED ISSUE #1583: Pedal Request: Daredevil Pedals Drive-Bi
4 5/8" x 3"

image

### LINKED ISSUE #1584: Pedal Request: Foxgear T7E Baby
5"x4"

image

### LINKED ISSUE #1585: Pedal Request: Headrush MX5
Please add the Headrush MX5. Thanks

### LINKED ISSUE #1586: Pedal Request: Vahlbruch Kaluna Hot Mod (High Gain Version)
Same dimensions as gold Kaluna (Dimensions: 120mm x 100mm x 48mm). Thanks!!

Kaluna

### LINKED ISSUE #1587: Pedal Request: Stomp Under Foot Silverfish
120mm x 100mm x 65mm

Silverfish

Thanks!

### LINKED ISSUE #1588: Mortrix midi controller needs to be added
This ones missing from the list please add

### LINKED ISSUE #1589: BOSS DM-101
dm-101

Gotta see this new bad boy! Surprised nobody else has asked yet

### LINKED ISSUE #1590: Pedal Request: Snake Oil Fine Instruments The Very Thing
4 5/16" x 2 1/2"

image

### LINKED ISSUE #1591: Pedal Request: Lovepedal Hermida Tiki
4 1/4" x 2 1/2"

image

### LINKED ISSUE #1592: Pedal Request: NuX Phaser Core
Width: 2.95
Height: 4.8

NUX Phaser Core

### LINKED ISSUE #1593: Pdeal Request: Engl Cabloader
Engl Cabloader_transparent

Dimensions:

4.43 x 3.75 x 2.17

### LINKED ISSUE #1594: Pdeal Request: Peacehill FX SSS Preamp
Peacehill SSS_transparent

Peacehill FX SSS preamp. 

Dimensions:
7.09 x 4.73 x 1.97

### LINKED ISSUE #1595: Pdeal request: MOSKY Ch-Vibe
Dimensions (L/W/H): 92mm X 38mm X 36mm

### LINKED ISSUE #1597: Please add MONO Pedalboard Rail
Please help to add the new MONO Pedalboard Rail range of products.

Small: https://monocreators.com/products/pedalboard-rail-small-black-and-stealth-club-accessory-case-black
18” x 13.3” x 3.7” (45.5 x 33.9 x 9.4cm)
https://cdn.shopify.com/s/files/1/2098/9809/files/products_2FPFX-PBR-S-BLK-BDL_2FPFX-PBR-S-BLK-BDL_1688956896984.jpg

Medium: https://monocreators.com/products/pedalboard-rail-medium-black-and-stealth-tour-accessory-case-black
24” x 14.4” x 3.7” (60.8 x 36.7 x 9.4cm)
https://cdn.shopify.com/s/files/1/2098/9809/files/products_2FPFX-PBR-M-BLK-BDL_2FPFX-PBR-M-BLK-BDL_1688957021974.jpg

Large: https://monocreators.com/products/pedalboard-rail-large-black-and-stealth-pro-accessory-case-black
32” x 16.7” x 3.7” (80.9 x 42.4 x 9.4cm)
https://cdn.shopify.com/s/files/1/2098/9809/files/products_2FPFX-PBR-L-BLK-BDL_2FPFX-PBR-L-BLK-BDL_1688613655484.jpg

Problem may be though that the brand hasn't utilised any photos of the products that are directly top down.

### LINKED ISSUE #1598: Pedal Request: XSONIC AIRSTEP Smart Multi Controller
Dimensions: 

Width: 11.81
Height: 2.76
 
XSONIC-Airstep-Smart-Multi-Controller

### LINKED ISSUE #1599: Pedal Request: Carl Martin Purple Moon Vintage Fuzz n 'Vibe V2
4.52" x 2.36"

CM Purple Moon Vintage Fuzz n 'Vibe V2 3

### LINKED ISSUE #1600: Pedal Request: Mono Power Supply
Three models:
Small: https://au.monocreators.com/products/power-supply-small
Medium: https://au.monocreators.com/products/power-supply-medium-au
Large: https://au.monocreators.com/products/power-supply-large-au

### LINKED ISSUE #1601: Pedal Request: Aclam Dr. Robert – Unknown Pleasures
"Brand": "Aclam",
"Name": "Dr. Robert – Unknown Pleasures",
"Width": 5.4,
"Height": 3.4,
"Image": "aclam-dr-robert-unknow-pleasures.png"
aclam-dr-robert-unknow-pleasures

### LINKED ISSUE #1602: Pedal Request: Carl Martin Compressor Limiter
4.72" x 3.74"

Carl Martin Compressor Limiter 2

### LINKED ISSUE #1603: Pedal Request: Vick Audio Tree of Life
Dimensions: 4.33" x 2.66" including jacks.

Tree of Life

### LINKED ISSUE #1604: Board Request: Voodoo Lab Dingbat Tiny
Please add this board.

### LINKED ISSUE #1605: ampero mini
can you please upload/update an ampero mini pedal on the pedal list?

### LINKED ISSUE #1606: JHS Bun Runner
can you please upload/update pedal on the list? 
Screenshot 2023-08-07 at 7 56 14 PM

### PR DESCRIPTION
**Pull request by ArislanShiva**
**Added:**
- 1981 LVL
- Aclam Dr. Robert (Unkown Pleasures)
- Aion Achilles
- Aion Aphelion
- Aion Aurora
- Aion Corvus
- Aion Maelstrom
- Aion Prism
- Aion Theseus
- Aion Vulcan
- Alexander Luminous
- AllPedal 1987
- AllPedal Devil's Triad
- Analog.man ARDX20 Dual Analog Delay
- Analog.man Envelope Filter
- Analog.man King of Tone (White)
- Analog.man Mini Bad Bob
- Animal Pedals Rover Fuzz V1
- Asheville AFG-1
- Beetronics Octahive 2
- Benevale Colt 45
- Benson Stonk Box
- Blackhawk Balrog V3
- Blammo! Deth Pedal
- Blammo! P2P Buzz Tone
- Bleak District Electric Tapescape
- Bluguitar Amp1 Iridium Edition
- Blue Colander Pig
- BOSS DM-101
- BOSS GM-800
- BOSS SDE-3000D
- BOSS SDE-3000EVH
- Browne Amplification Gritador
- Carl Martin Compressor Limiter
- Carl Martin Purple Moon
- Catalinbread Carbide
- Catalinbread Tremolo8
- Champion Leccy The Dunsh
- Chase Bliss Generation Loss MKII (LE)
- Chase Bliss MOOD MKII (LE)
- Chase Bliss Reverse Mode C
- CIOKS DC10 Link
- Cornerstone Colosseum
- Coppersound Iris
- Coppersound Kingpin
- Cusack Resound V2
- Cusack Tap-A-Phase
- Cusack Tap-A-Whirl V4
- D'Addario XPND1
- D'Addario XPND2
- Damnation Audio Curmudgeon Dist 2
- Damnation Audio MBD2
- Daredevil Almighty Bass
- Daredevil Atomic Cock
- Daredevil Bootleg Dirty Delay V2
- Daredevil Cocked & Fearless
- Daredevil Daisho
- Daredevil Drive-Bi
- Daredevil Northern Creeper
- Daredevil Premium Overdrive
- Daredevil Real Cool Fuzz
- Daredevil Silver Solo
- Dark Glass Hyper Luminal (Black)
- Death By Audio Disturbance
- Diamond Bass Comp/EQ (2023)
- Diamond Boost-EQ
- Diamond Boost-EQ 2
- Diamond Comp/EQ (2023)
- Diamond Drive (2023)
- Diamond Memory Lane (2023)
- Diamond Tremolo (2023)
- Diffractor Soundings Arboretum
- DOD FX-50 Overdrive Preamp
- Does It Doom Doomcaster
- Dr. Scientist BoostBot
- Dut Beardy Admiral
- EAE 0XEAE Boost
- EAE 0XEAE Fuzz
- EAE Sending v2
- EAE Dagger (Black)
- EHX Deluxe Electric Mistress (Big Box)
- EHX Green Russian Big Muff Pi
- EHX Hell Melter
- EHX Q-Tron (Big Box)
- EHX Pico POG
- EHX Walking on the Moon
- Electrode Mercury Tube Fuzz
- Empress Heavy Menace
- Engl Cabloader
- Eno Music EX EQ 7
- EQD Disaster Transport (Parra)
- EQD Disaster Transport (Reissue)
- EQD Ledges
- E.W.S. Japan Little Fuzz Drive
- Fender Shields Blender
- Fjord Fuzzy Loke
- FMR RNC
- Foxgear T7E Baby
- Freethetone PHV-1
- Fuzzrocious Afterlife
- Fuzzrocious Baby Blast Furnace
- Fuzzrocious Knob Jawn
- Fuzzrocious Heliotropic
- Fuzzrocious M.O.T.H.
- Fuzzrocious Playing Mantis
- Fuzzrocious Tyrannochorus
- Gamma Atlas
- Gamma Bacchus
- Gamma Cumulus
- Gamma Eros
- Gamma Hades
- Gamma Narcissus
- GigRig Generator
- GigRig GenX14
- GigRig Midi Driver
- Headrush MX5
- Hello Sailor Effects Rangemaster
- HiWatt Filter Fuzz MK2
- Homebrew Electronics Power Screamer
- Horrothia FX Teeth MKII
- Hotone Ampero Mini
- Intensive Care Audio Death Drive
- Intensive Care Audio Fideleater
- Intensive Care Audio Vena Cava Filter
- Interstellar Audio Machines Fuzzsquatch Fuzzdrive
- Interstellar Audio Machines Marsling Octafuzzdrive
- Interstellar Audio Machines Octonaut Hyperdrive
- J. Rockett HRM V2
- J. Rockett Uni-Verb
- Jackson Audio Golden Boy Mini
- Jackson Audio Golden Boy Mini (Black)
- JAM Boomster mk2
- JAM Fuzz Phrase Ltd
- JDM Humdinger
- Jetter Red Square
- JHS Bun Runner
- Joyo R-21
- Joyo R-22
- Joyo R-24
- Joyo R-26
- Joyo R-27
- Joyo R-28
- Keeley Delay Workstation
- Keeley Super AT Mod
- Keeley Time Machine Boost
- Keith McMillen Instruments 12 Step
- Korg HD-S
- Land Devices EP-5
- Land Devices HP-2 (White)
- Land Devices No Masters
- Land Devices Pre (Black)
- Lovepedal Hermida Tiki Drive
- Lwave Tiny Tap
- Milkman The Amp Stereo
- Mod Audio Dwarf
- Moen GEC5
- Mono Power Supply (Large)
- Mono Power Supply (Medium)
- Mono Power Supply (Small)
- Mono Rail (Large)
- Mono Rail (Medium)
- Mono Rail (Small)
- Mooer Drummer X2
- Mooer Looper X2
- Mooer Micro Drummer II
- Mooer Micro Looper II
- Mosky Ch-Vibe
- Mr. Black JDD-3000
- Musicom Labs Parallelizer
- MXR Custom Shop Hybrid Fuzz
- Mythos Hephaestus
- Mythos Hephaestus V2
- Native Audio Buffalo Days
- Native Audio Mint Drive
- Native Audio Two Medicine
- Nordland ODR-CS
- NuX '6ixty5ive
- NuX Hook
- NuX Phaser Core
- NuX Trident
- O.C.E. Pedals Wrench Fuzz
- OBNE BL-37
- OBNE MTET
- Oneder Old Blue
- Orange Amp Detonator
- Origin Effects Halcyon Gold
- Palmer Pocket Amp MK2
- Paul Cochrane Tim V3
- Peace Hill FX SSS Tube Preamp
- Pedal Brainz 3rd eye
- Pedal Brainz Left Brain
- Pedal Brainz No-Brainer
- Pedal Pawn Chicken Quiff
- Pedal Pawn Fuzz
- Pedal Pawn Germanium Fuzz
- Pedal Pawn Gypsy Vibe
- Pedal Pawn Octone
- Pedal Pawn Texas Twang
- Pedaltrain Daylight
- Pedaltrain Grande
- Pedaltrain Nightlight
- Pedaltrain XD-18
- Pedaltrain XD-24
- Pigtronix Mothership 2
- Pigtronix Resotron
- Providence System Tuner STV-1JB
- Radial JDX Direct Drive
- Revv Chat Breaker
- Rockboard by Warwick Tres 3.3
- Roger Mayer Voodoo Vibe
- Sabbadius Funky Vibe
- Shnobel Tone Boost
- Shnobel Tone Buffer
- Shnobel Tone Buffer Fuzz Interface
- Shnobel Tone Compressor
- Shnobel Tone Daily Driver
- Shnobel Tone Daily Driver Stereo
- Shnobel Tone Dunlop Mini Volume+
- Shnobel Tone Horse Power
- Shnobel Tone Mid Driver
- Shnobel Tone Ratatouille
- Shnobel Tone Volume/Expression Selector Box
- Smallsound/Bigsound Mini (Pink)
- Smallsound/Bigsound Mini (Top Jacks)
- Snake Oil Marvellous Engine
- Snake Oil Fine Instruments The Very Thing
- Soma Cosmos
- Sonicake Faze Cream
- Sonicake Noise Wiper
- Sonicake Octaver
- Sonicake Rude Mouse
- Sonicake Sonic Ambience
- Sonicake Sonic Dub
- Sonicake Sonic IR
- Sonicakr Wave Crush
- Spaceman Meridian
- Stompbox EX Portable 20
- Stone Deaf Qboost (LE)
- Strymon Brig
- Subdecay Anamnesis Echo
- Subdecay Harmonic Antagonizer
- Subdecay Liquid Sunshine
- Subdecay M3
- Subdecay Octave Theory
- Subdecay Pixelwave
- Subdecay Prometheus 3
- Subdecay Prometheus DLX
- Subdecay Proteus
- Subdecay Quasar
- Subdecay Quasar DLX
- Subdecay Siren
- Subdecay Starlight
- Subdecay Starlight DLX
- Subdecay Super Spring Theory
- Subdecay Supernova Drive
- Subdecay TremCoder
- Subdecay Tremcode MkII
- Subdecay Variac
- Subdecay Vector
- Subdecay Vitruvian Mod
- Surfy Industries SurfyFuzz
- Tape Audio Co. One
- Tape Audio Co. Two (Black)
- Tape Audio Co. Two (White)
- TC Electronic Ampworx Combo Deluxe 65'
- TC Electronic Ampworx DC30
- TC Electronic Ampworx Jims 45
- TC Electronic Infinite Mini Sample Sustainer
- TC Helicon Harmony-G XT
- Templo Model 33
- Templo Real Dealuxe
- Templo Splyce
- Tone City King of Blues
- Tone City Model M
- Tru-Fi Floyd Fuzz
- Twilight Pulse Audioworks Konstante
- Twilight Pulse Audioworks Proxima
- Vahlbruch Kaluna (High Gain)
- Van Weeden Royal Overdrive
- Vick Audio Tree of Life
- Volta 1987 Pro
- Voodoo Labs Dingbat Tiny
- VS Audio Platinum
- Walrus Audio Slöer
- Walrus Audio Slöer (Black)
- Warm Audio Mutation Phasor II
- Warm Audio ODD Box
- Westerlund One
- Xotic Soul 
- Xotic Robotalk 2
- Xotic Soul Driven
- Xotic SP X-Blender
- Xotic XVP-25k
- Xsonic Airstep
- Zvex Instant Lo-Fi Junky (Yvette)
- Zvex Box of Rock Vertical (Yvette)

**Updated:**
- Aion various artwork + dimensions
- AllPedal various dimensions
- Analog.Man various artwork + dimensions
- BOSS various artwork + dimensions
- Cornerstone various artwork
- Cusack Tap-A-Whirl (Red) artwork + dimensions
- Donner various dimensions
- EAE Sending dimensions
- Empress various artwork
- Fjord Fuzz various artwork + dimensions
- Fuzzrocious various artwork + dimensions
- GigRig various artwork + dimensions
- Greer various artwork + dimensions
- Land Devices various artwork + dimensions
- Line 6 HX Stomp artwork
- Milkman artwork + dimensions
- NuX various artwork + dimensions
- Oneder Red Ryder artwork + dimensions
- Pedaltrain various artwork
- Smallsound/Bigsound Mini artwork + dimensions
- Subdecay various artwork + dimensions
- Vahlbruch Kaluna artwork + dimensions
- Walrus Audio artwork + names
- Warm Audio Foxy Tone Box artwork + dimensions
- Xotic various artwork + dimensions
- Zvex various artwork + dimensions
- Cleaned up ReadMe request instructions

**Fixed:**
- Brand label issues from #1437 
- Donner Tutti Love dimensions
- Stomp Audio Labs Octopus file fix

**Merging** (trying to clear the backlog of old PRs):
- #1470
- #1468
- #1214
- #1143

closes #1606
closes #1605
closes #1604
closes #1603
closes #1602
closes #1601
closes #1600 
closes #1599
closes #1598
closes #1597
closes #1595
closes #1594
closes #1593 
closes #1592 
closes #1591
closes #1590
closes #1589
closes #1588
closes #1587
closes #1586
closes #1585
closes #1584
closes #1583
closes #1582
closes #1581
closes #1580
closes #1579
closes #1578
closes #1577
closes #1576
closes #1575
closes #1574 
closes #1572
closes #1571
closes #1570
closes #1569
closes #1568 
closes #1567
closes #1563
closes #1562
closes #1561
closes #1559
closes #1557
closes #1556
closes #1555
closes #1554
closes #1552
closes #1551
closes #1548
closes #1545
closes #1544 
closes #1543 
closes #1542
closes #1541
closes #1538
closes #1537 
closes #1535
closes #1534
closes #1533
closes #1532
closes #1531
closes #1530
closes #1529
closes #1528 
closes #1527
closes #1526
closes #1525
closes #1524
closes #1523
closes #1522
closes #1521
closes #1520
closes #1519
closes #1517
closes #1516
closes #1515
closes #1512
closes #1511
closes #1510
closes #1509
closes #1508
closes #1507
closes #1505
closes #1492
closes #1490
closes #1488
closes #1480
closes #1448
closes #1432
closes #1416
closes #1204

### CODE REVIEW

**Comment by XlosVSM** [comment]
closes #1559

**Comment by ddejohn** [comment]
ETA on this PR? Been wanting to add an Empress Heavy Menace to my layout for weeks :)

**Comment by ArislanShiva** [comment]
> ETA on this PR? Been wanting to add an Empress Heavy Menace to my layout for weeks :)

I'm not sure, It's out of my control.

You can actually [download my repo](https://github.com/ArislanShiva/PedalPlayground.github.io) and [run it locally](https://github.com/ArislanShiva/PedalPlayground.github.io#running-locally) on your machine if you can't wait.

**Comment by XlosVSM** [comment]
closes #1577

**Comment by versuswhat** [comment]
hey guys - thanks for the all amazing work here. Any idea when builds for 1593 and 1594 might get done? cheers.

**Pull request merged**
