### PR TITLE
new pedals

### PR DESCRIPTION
**Pull request by apeekaboo**
Hi,

My name is Tobbe and I would like to contribute some pedals to the project; BluGuitar Amp1 and AMT GR-4. I'm totally new to working with github, so I hopefully I'm on the right track here.

Cheers

### CODE REVIEW

**Comment by tehtrav** [comment]
The BluGuitar pic has a little extra empty space around the image, would you mind trimming that a bit? Otherwise it will appear smaller than it should be on the site.

**Comment by apeekaboo** [comment]
I've updated both images now as I saw there was room for improvements on both.

**Comment by tehtrav** [comment]
Nice job. Thank you!

**Comment by apeekaboo** [comment]
Thanks! Looking forward to the new release!
Now that I've added my first pedals, I have a few more to add.

Cheers

**Pull request merged**
