### PR TITLE
Added Deadbeat and a few other pedals from requests.

### PR DESCRIPTION
**Pull request by XlosVSM**
First pull request was a mistake. Here is the proper version. Photos have been added into app, but couldn't put it into public.

### CODE REVIEW

**Comment by XlosVSM** [comment]
> The images need to be trimmed down to remove the transparent pixels, otherwise they'll get sized down way too small

@tehtrav I am new at this so could explain in a bit more depth?

**Comment by ArislanShiva** [comment]
What he means is you need to crop your images and lose all the dead space around each pedal.

**Comment by tehtrav** [comment]
@XlosVSM as @ArislanShiva said, you need to crop the image closer to the pedal so the bounds of the image match the edges of the pedal. As an example: https://www.pedalplayground.com/public/images/pedals/tc-tailspin.png

Not sure what you're using to cut pedals out but in Photoshop you would go to Image > Trim and then select Based on Transparent Pixels

**Comment by XlosVSM** [comment]
Closed so improvements can be made.

**Pull request closed without merging**
