### PR TITLE
Added Chase Bliss + Keeley + Walrus + DBA + BNE + Land Devices + Fairfield + SGFX + Pigtronix + 29 Pedals + Southampton + Jam pedals + One Control

### PR DESCRIPTION
**Pull request by ArislanShiva**
Added:
- Chase Bliss Ayahuasca
- Chase Bliss Generation Loss
- Chase Bliss Tonal Recall RKM
- Chase Bliss Warped Vinyl HiFi
- Chase Bliss Warped Vinyl MKII
- Chase Bliss Wombtone MKII

Updated art:
- Chase Bliss Dark World
- Chase Bliss Faves
- Chase Bliss Midibox
- Chase Bliss Spectre
- Chase Bliss Tonal Recall
- Chase Bliss Warped Vinyl

Fixed:
- Dimensions of various pedals

### CODE REVIEW

**Comment by ArislanShiva** [comment]
Added EQD Erupter

**Comment by ArislanShiva** [comment]
Added:
- TC Electronics Ditto+
- BOSS RC-500 Loop Station

**Comment by ArislanShiva** [comment]
Added:
- Walrus Audio Deep Six V2
- Walrus Audio Jupiter V2
- Walrus Audio Luminary V2
- Walrus Audio SLARP
- Walrus Audio Warhorn / Ages Dual Drive

Edited dimensions and artwork for many other WA pedals

**Comment by ArislanShiva** [comment]
Added:
- Beautiful Noise Experiments Endless Sleeper
- Beautiful Noise Experiments When the Sun Explodes
- Collision Devices Black Hole Symmetry
- Death by Audio Absolute Destruction
- Death by Audio Apocalypse
- Death by Audio Deep Animation
- Death by Audio Harmonic Transformer
- Death by Audio Interstellar Overdrive Deluxe
- Death by Audio Rooms
- Death by Audio Soundwave Breakdown
- Death by Audio Sonic Annihilation 2
- Solid Gold FX EM-III
- Solid Gold FX Imperial MkII
- Solid Gold FX Oblivion

Edited:
- Artwork for all DBA pedals

**Comment by ArislanShiva** [comment]
Added:
- GFI Clockwork v2
- GFI Clockwork V3

Updated artwork:
- Caroline Shigeharu
- Caroline Icarus
- Champion Leccy Skitter

**Comment by ArislanShiva** [comment]
Added:
- Pro Co Rat 2
- Pro Co Lil' Rat
- Southampton Boosted Fuzz
- Southampton Fifth Gear
- Southampton Ictenio
- Southampton Indie Dream
- Southampton Utility Knife

**Comment by ArislanShiva** [comment]
Added:
- Fairfield Hors d'Oeurves?
- Fairfield Long Life
- Land Devices Domino
- Land Devices Land Mixer
- Land Devices Pre

Edited:
- Smallsound/Bigsound artwork updates

**Comment by ArislanShiva** [comment]
Added:
- Benson Germanium Fuzz
- EQD Sea Machines V1
- EQD Sea Machines V3

Edited:
- Champion Leccy The Skitter artwork

**Comment by ArislanShiva** [comment]
Added:
- Champion Leccy The Swan Hunter
- Jam Pedals CTRL BOX
- Jam Pedals Delay Llama Xtreme
- Jam Pedals Dyna-ssoR
- Jam Pedals Eureka!
- Jam Pedals Pink Flow
- Jam Pedals Ripple
- Jam Pedals Wahcko
- Jam Pedals Red Much

Edited:
- Assorted Jam Pedals dimensions and artwork

**Comment by ArislanShiva** [comment]
Added:
- Keeley Aurora
- Keeley Bubble Tron
- Keeley Caverns V1
- Keeley DDR
- Keeley El Rey Dorado
- Keeley Fuzz Bender
- Keeley GC-2
- Keeley Hooke Reverb
- Keeley Katana Throwback White Edition
- Keeley Mini Katana
- Keeley Monterey
- Keeley Noctuner
- Keeley Omni
- Keeley Seafoam
- Keeley Synth-1
- Keeley VoT Workstation
- Keeley XVIII Phaser

Edited:
- Various Keeley artwork and pedal dimensions

**Comment by ArislanShiva** [comment]
Added:
- 29 Pedals EUNA
- 29 Pedals OAMP
- Pigtronix Class A Boost
- Pigtronix Constellator
- Pigtronix Infinity Looper 3
- Pigtronix Moon Pool
- Pigtronix Philosopher's Tone Germanium Gold
- Pigtronix Space Rip
- Pigtronix Universal Remote

**Comment by ArislanShiva** [comment]
Added:
- Red Panda Bitmap 2
- Red Panda Buffer
- Red Panda Context 2
- Red Panda Mixer
- Red Panda Raster 2
- Red Panda Remote 4
- Vertex Ultraphonix MKII

**Comment by romaintb** [comment]
Dwayne Johnson clapping

**Comment by ArislanShiva** [comment]
Added:
- One Control 1Loop Box
- One Control AB Box
- One Control Basilisk
- One Control BJF Buffer
- One Control BJF Buffer Split
- One Control Black Loop
- One Control Caiman Tail Loop
- One Control Croc Eye
- One Control Crocodile Wing Tail Loop
- One Control Gecko MkIII
- One Control Junction Box
- One Control MIDI Solo Stereo Loop
- One Control Mosquito Blender
- One Control Pedal Board Junction Box 4M
- One Control Tuner
- One Control White Loop

Edited:
- Various One Control artwork + dimensions

**Comment by tehtrav** [comment]
This is an insane amount of work you put in, thank you!!! Merging this in now.

**Comment by ArislanShiva** [comment]
> This is an insane amount of work you put in, thank you!!! Merging this in now.

I've been leaving comments on the pedal requests that I've completed if that makes it easier for you to close the issues.

**Comment by romaintb** [comment]
@ArislanShiva you can use the syntax `closes #123` in your pull request message to automatically close issues on merge ;)

**Comment by ArislanShiva** [comment]
OMG, thanks!

**Pull request merged**
