### PR TITLE
Adds 1981 Inventions, Becos, Collaboration Devices, Donner, Dunlop, and other requests

### LINKED ISSUE #936: Pedal request: MOOER BABY BOMB
mooer_babybomb

W: 1.65in
H: 3.66in

### LINKED ISSUE #938: Pedal Request: Dunlop CAE Crybaby
Size: 4" x 10"

Dunlop CAE Crybaby 350
Dunlop CAE Crybaby 800

### LINKED ISSUE #939: Pedal Request: 1981 Inventions DRV Outline
"Name": "DRV (Outline)",
"Width": 3.7,
"Height": 4.57,

outline350
outline800

### LINKED ISSUE #940: Pedal Request: Hudson Broadcast (Orange)
"Brand": "Hudson",
"Name": "Broadcast (Orange)",
"Width": 4.7,
"Height": 3.84,

broadcast350
broadcast800

### LINKED ISSUE #979: Pedal request: Wampler Plexi Drive
BA9B3C11-2CCC-4580-8491-9526F60C165A

### LINKED ISSUE #985: Pedal request: VICK AUDIO 1861
W: 2.25 in
H: 4.75 in

vick_audio_1861

### LINKED ISSUE #986: Pedal request: VICK AUDIO '73 RAM'S HEAD
W: 2.25in
H: 4.25in

vick_audio_73_ramshead

### LINKED ISSUE #987: Pedal request: VICK AUDIO V2
W: 3.70 in
H: 4.72 in

vick_audio_V2

### LINKED ISSUE #988: Pedal request: DONNER JET CONVOLUTION
W: 1.43in
H: 3.64in

donner_jet_convolution

### LINKED ISSUE #989: Pedal request: DONNER NOISE KILLER
W: 1.43in
H: 3.64in

donner_noise_killer

### LINKED ISSUE #990: Pedal accessory request: CM/INCH Scale
Size: 4" x 1"

cm_inch scale

### LINKED ISSUE #1004: Pedal request: ROWIN TUNER
W: 1.43in
H: 3.64in

rowin_tuner

### LINKED ISSUE #1006: Pedal request: MXR JHM3 JIMI HENDRIX UNI-VIBE
H: 4.33in
W: 2.56in

MXR_JHM3

### LINKED ISSUE #1007: Pedal request: BECOS Ziffer Overdrive – Jordan Ziff Signature MINI Pedal
[https://becosfx.com/product/ziffer-jordan-ziff-signature-analog-mini-overdrive-tubescreamer/](url)

Dimensions: 3.9 × 9.2 × 5.1 cm

image

### LINKED ISSUE #1008: Pedal Name Update
Hi
Please change the "NUX Flow" to "NUX FLOW TUNE", which is the official name of the unit.
I'd try to pull requests to change the name but it seems like no result, I'm not sure if i'm not qualified?
So please help me to change the name
Thank you.

### LINKED ISSUE #1012: Pedalboard request: Palmer Pedalbay 60
Hi, can you please add this board?

Measures are:
Width 605mm
Depth 305mm

Thanks

Palmer_PEDALBAY60

### PR DESCRIPTION
**Pull request by XlosVSM**
**Adds**
- 10cm/4" Ruler
- 1981 Inventions DRV Outline
- BECOS Ziffer Overdrive
- Collaboration Devices The Compressor
- Donner Jet Convolution
- Donner Noise Killer
- Dunlop CAE Crybaby
- Hudson Broadcast (Orange)
- MXR JHM3
- Palmer Pedalbay 60 
- Rowin Tuner
- Vick Audio '73 Ram's Head
- Vick Audio 1861
- Vick Audio V-2

closes #936 (already in)
closes #938 
closes #939 
closes #940 
closes #979 
closes #985 
closes #986 
closes #987 
closes #988 
closes #989 
closes #990 
closes #1004 
closes #1006 
closes #1007 
closes #1008 
closes #1012

### CODE REVIEW

**Comment by dvr994** [comment]
why the #936 issue is already in? What does it mean?

**Comment by romaintb** [comment]
@dvr994 the baby bomb is already listed :)
image

**Comment by dvr994** [comment]
> @dvr994 the baby bomb is already listed :) image

Ok, my error.

**Comment by btbrown22** [comment]
#980 has not been added

**Review by ArislanShiva — CHANGES_REQUESTED** [review]
Added the Jackson Audio Modular Fuzz with a cleaner image in my PR.

**Comment by dvr994** [comment]
Vick Audio 73' ram's head*, not 78.

**Comment by XlosVSM** [comment]
@ArislanShiva is there something wrong that I need to fix which is stopping this from merging?

**Comment by flaviourubu** [comment]
@XlosVSM CAE Wah correct size is:

 		"Width": 4,
		"Height": 10,

**Pull request merged**
