### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Silenceborn**
Uploaded images for "/public/images/pedals"

### CODE REVIEW

**Comment by tehtrav** [comment]
In the future please put all images and json in one pull request. Thanks!

**Comment by Silenceborn** [comment]
Sure, I noticed that it probably is not the most ideal way to set them separately, but although I was looking for it, I could not find a way to put them all in one pull request? Would you be kind enough to shed some lights on this please? Cheers,

**Comment by Silenceborn** [comment]
When I go to my fork, I need to go to the folders where the images need to be uploaded, when I upload them, if I leave the page the uploaded files will be removed. So how can I have them all under one pull request? Thanks again

**Comment by tehtrav** [comment]
I am not exactly sure as i don't use the github uploader but you need to make sure all your changes are being done to the same **branch**. That way when that branch is merged in, all changes will come with it at once. 

Thanks again!

**Pull request merged**
