### PR TITLE
Add images and data for Morton Pedalboards

### PR DESCRIPTION
**Pull request by AdrianDAlessandro**
Adding in the images and data for exciting new, modular pedalboards company [Morton Pedalboards](https://mortonpedalboards.com)

### CODE REVIEW

**Comment by AdrianDAlessandro** [comment]
If this needs any additional context, please let me know @tehtrav

It should be simple enough, I followed contributing instructions and have just added the full range of pedalboards from Morton. I noticed there is only one folder of png's for pedalboards, so I just used the 350px images. It appears to work fine when I run it locally.

**Comment by tehtrav** [comment]
Looks good! Merging...

**Comment by tehtrav** [comment]
On second look, I'll leave these up but if you're able to commit higher res PNGs for the pedalboards they will look much better. You can make them at least 2-3x the size they are currently.

**Comment by AdrianDAlessandro** [comment]
> On second look, I'll leave these up but if you're able to commit higher res PNGs for the pedalboards they will look much better. You can make them at least 2-3x the size they are currently.

Thank you for the suggestion @tehtrav. I've forwarded it on to Morton for their consideration.

**Pull request merged**
