### PR TITLE
Added Vertex Pedalboards + Classic Audio Effects + Effects Bakery + Free The Tone + Newly Released Pedals + Requests

### PR DESCRIPTION
**Pull request by ArislanShiva**
Added:
- Analog.man Bi-CompROSSor REV5
- Analog.man Envelope Filter
- Anasounds Savage MK1 Reissue
- Black Mass 1312 v3
- Black Mass Missionary v2
- Black Mass The First Herald
- BNE When the Sun Explodes (Pastel Pink)
- BNE When the Sun Explodes (Powder Blue)
- BNE When the Sun Explodes (Seafoam Green)
- Bondi Sick As (Custom Black)
- Bondi Sick As (Custom Blue)
- BOSS FZ-1w
- Chase Bliss EXP
- CAE Aloft
- CAE Amethyst
- CAE Amethyst Mini
- CAE Cliffside
- CAE Expression Roller
- CAE Foothills
- CAE Passive Volume Roller G2
- CAE Stump House
- CAE Transponder
- CAE Transponder Delay Roller
- CAE Yukon
- Effects Bakery An Bread DI
- Effects Bakery An Butter Coppe
- Effects Bakery Bagel Overdrive
- Effects Bakery Choco Cornet EQ
- Effects Bakery Cream Pan Booster
- Effects Bakery Croissant Distortion
- Effects Bakery Curry Bread Junction Box
- Effects Bakery French Bread Delay
- Effects Bakery Melon Pan Chorus
- Effects Bakery New Ginger Fuzz
- Effects Bakery Plain Bread Compressor
- Effects Bakery Sandwich Fuzz
- EQD Hizumitas
- FTT Black Vehicle
- FTT Crunchy Time
- FTT DVL-1
- FTT Final Booster
- FTT Fire Mist
- FTT Future Factory
- FTT Heat Blaster
- FTT Motion Loop
- FTT PA-1QG
- FTT Quad Arrow
- FTT Silky Comp
- FTT Silky Groove
- FTT SOV-2 Overdrive
- FTT String Slinger
- Marshall Blues Breaker
- Matthews Astronomer
- Matthews The Broker
- Matthews The Ghoul
- Native Audio Pretty Bird Woman
- SGFX Ether
- Vertex Tour Compact
- Vertex TC1 Riser
- Vertex TC2 Riser
- Vertex TC3 Riser
- Vertex Tour Elite
- Vertex TE1 Riser
- Vertex TE2 Riser
- Vertex TE3 Riser
- Vertex Travel Light
- Vertex TL1 Riser
- Vertex TL2 Riser
- Vertex Travel Plus
- Vertex SSS Srv
- Vertex TP1 Riser
- Vertex TP2 Riser
- Walrus ARP-87 Platinum
- Walrus Julia V2 Platinum

Edited:
- BOSS BD-2 artwork
- Various Free the Tone artwork + dimensions
- Various Matthews Effects artwork + dimensions

### CODE REVIEW

**Comment by ArislanShiva** [comment]
Any chance I could get access to push PRs?

**Comment by XlosVSM** [comment]
Also closes #182

**Comment by ArislanShiva** [comment]
> Also closes #182

Good call, thanks!

**Comment by tehtrav** [comment]
This will need some cleanup since the other PR reordered a lot of pedals

**Comment by ArislanShiva** [comment]
Resolve conflicts is grayed out.

**Pull request closed without merging**
