### PR TITLE
Adds Ampeg, Catalinbread, Darkglass, Donner, EarthQuaker Devices, Friedman, J. Rockett, Jackson Audio, Keeley, and Line 6 pedals

### LINKED ISSUE #1446: Improvement/fix: Dimensions of "Donner AB/Y" too small
The "Donner AB/Y" has pretty much the same dimensions as the "Mooer Micro ABY MKII".

Dimensions "Donner AB/Y": **42x93.5x52mm** (https://donnerde.com/products/donner-aby-box-gitarre-effektpedal-aby-kanalschalter-mini-gitarre-pedal-true-byapss)

As you can see in the attached screenshot, the "Donner AB/Y" appears way smaller though (the dimensions of the "Mooer Micro ABY MKII" fit to the rest of the pedals on my virtual board)

Bildschirm­foto 2023-03-08 um 00 05 52

### LINKED ISSUE #1453: Kingsley Page TS
Width: 3.875 inches
Height: 4.75 inches

kingsleypagets675

### LINKED ISSUE #1469: DBA Interstellar Overdriver
The pedal exists in the data base, but there is no image. The same applies for it's brother, the Interstellar Overdriver Deluxe. Although this one has an image, it's image is the non deluxe version stretched.
DBA Interstellar Overdriver v2
DBA Interstellar Overdriver Deluxe

### LINKED ISSUE #1472: Sonuus - Voluum
Sonuus Voluum

Dimensions: 7.2 x 8.3"
(these measurements factor in the protrusion of the foot rocker beyond the pedal housing)

### LINKED ISSUE #1473: Pedal Requests: GUPTech - SUN Noise Gate, MOYO - Mini Expression, MOYO - Mini Volume
GUPtech SUN Noise Gate
GUPTech SUN Noise Gate Dimensions: 3" x 5" including jacks

MOYO Mini Expression
MOYO Mini Expression Dimensions: 2.125" x 6"

MOYO Mini Volume
MOYO Mini Volume Dimensions: 2.125" x 6"

### LINKED ISSUE #1483: EHX x JHS Lizard Queen big box
Lizard+Queen (1)

6.875in x 5.5in

### LINKED ISSUE #1484: Pedal Request : Fulltone GT-500
Fulltone GT-500,  5.75" x 3.87" 
Screenshot_20230411-195727_Chrome

### LINKED ISSUE #1485: PastFX Patriarch request
Hopefully this image uploads and is sufficient. It's skewed clockwise by the slightest amount, but this is file the builder sent me. The dims are 112mm x 60mm / 4.4" x 2.36" 

PastFX Patriarch

### LINKED ISSUE #1486: PastFX Powerbooster
Dims 112 x 60 x 31mm / 4.4" x 2.36" x 1.22"
PastFX PB

### PR DESCRIPTION
**Pull request by XlosVSM**
**Adds**
- Ampeg SGT-DI
- Catalinbread Sabbra Cadabra (Clearwell Edition)
- Catalinbread Soft Focus Reverb (Shoegaze Purple)
- Darkglass NSG
- Donner Circle Looper
- Donner Dark Mouse
- Donner Dumbal Drive
- Donner Extreme Driver
- Donner Golden Tremolo
- Donner Island Delay
- Donner Morpher
- Donner Vintaverb
- EarthQuaker Devices Aurelius
- EarthQuaker Devices Special Cranker (Blue Steel)
- Electro-Harmonix Lizard Queen (Big Box)
- Friedman BE-OD (Artisan Edition)
- Friedman BE-OD Deluxe (Clockworks Edition)
- Friedman Sir-Compre (Artisan Edition)
- Fulltone GT-500
- GUPTech SUN
- J. Rockett Audio Designs The Jeff Archer (Copper Plated)
- Jackson Audio Golden Boy (Rose)
- Keeley Halo (Andy Apple Red)
- Keeley Katana (New Light Pink)
- Kingsley Page TS
- Line 6 Helix (Space Gray)
- Mooer TF-16S
- MOYO Mini Expression
- MOYO Mini Volume
- PastFX Patriarch
- PastFX Powerbooster
- Pladask Elekstrisk Falma V2
- Sonuus Voluum

**Fixes**
- Death by Audio Interstellar Overdriver image
- Dimensions of some Donner pedals
- DOD Carcosa image improved
- DOD moved to its own brand
- File name changes for spelling
- Restores brands on some pedals
- Restores Retro-Sonic images

closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1251
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1443
closes #1446 
closes #1453 
closes #1469 
closes #1472 
closes #1473 
closes #1483 
closes #1484 
closes #1485 
closes #1486

### CODE REVIEW

**Comment by ArislanShiva** [comment]
Yikes, you've got quite the mess here.  Instead of reuploading so many images, why didn't you just [revert the commit](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit) where you deleted the app folder?  Every new version of the image will balloon the repo even more (all versions are saved).

**Comment by XlosVSM** [comment]
> Yikes, you've got quite the mess here. Instead of reuploading so many images, why didn't you just [revert the commit](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit) where you deleted the app folder? Every new version of an image will balloon the repo even more (all versions are saved).

Was a mess, already been sorted.

**Comment by ArislanShiva** [comment]
> Was a mess, already been sorted.

That's a relief.

Looks like you've overwritten some app folder images with pedal folder images:

DOD 410
DOD FX63
DOD FX64
DOD FX65
DOD FX69
DOD FX75B
DOD Rubberneck
TC Flashback

Please revert those changes.  Thanks.

**Review by ArislanShiva — CHANGES_REQUESTED** [review]
Let's try to keep the brand labels as short as possible.  The drop down is pretty narrow.   Like I recently changed "Old Blood Noise Endeavors" to OBNE because that entire section was unreadable with all the word wrapping.  Simply "EarthQuaker" was fine.

**Pull request closed without merging**
